### ISSUE TITLE
Empty folders are skipped

### ISSUE THREAD

**Issue by enenra** [Gwindalmir/SEWorkshopTool#37]
When uploading an empty mod (for modpack purposes) the game requires there to at least be an empty Data folder in the mod's directory. SEWT seems to skip the inclusion of the empty Data folder. The ingame mod upload includes the Data folder as normal.

**Comment by Gwindalmir** [comment]
This happens if you have some files on your ignore list.
The game will copy your mod to a temporary location, and upload it from there.

To work around that, you would need to place a dummy file into the Data directory.
I might be able to detect it and place one myself, but I tend to not modify mods.
At the least, I could show a warning.
